name = "Ding"
uuid = "3926c259-39ba-4d74-9c2f-25ff6470b8c3"
authors = ["theogf <theo.galyfajou@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
